### ISSUE TITLE
Read an account from the service

### ISSUE THREAD

**Issue by raffaele-russo** [raffaele-russo/devops-capstone-project#10]
**As a** customer 
**I need**  to retreive a stored account 
**So that** I can access the related name and address

### Acceptance Criteria     
    gherkin 
    Given an existing account
    When the customer  retrieves the account by providing the valid information
    Then the system will return the customer's name and address

**Comment by aries2004-bit** [comment]
maybe this will help
https://bit.ly/4gwC82r
I put the necessary dlls in the archive
